ErikKalkoken/evebuddy

.gitignore
FyneApp.toml
internal/app/character/characterasset.go
internal/app/character/characterasset_internal_test.go
internal/app/character/charactermailupdate.go
internal/app/character/characterskills.go
internal/app/character/characterskills_internal_test.go
internal/app/storage/characterasset.go
internal/app/storage/characterasset_test.go
internal/app/storage/characterskill.go
internal/app/storage/characterskill_test.go
internal/app/storage/queries/character_assets.sql
internal/app/storage/queries/character_assets.sql.go
internal/app/storage/queries/character_skills.sql
internal/app/storage/queries/character_skills.sql.go
internal/app/ui/jumpclones.go
internal/app/ui/ui.go
main.go

- App title no longer includes character name
- Clicking on a jump clone no longer opens the location window directly
- 2 memory leaks (Deleting obsolete assets & Deleting obsolete skills)

Fixes & Improvements

---

FyneApp.toml
README.md
internal/app/evenotification/billing.go
internal/app/evenotification/billing_test.go
internal/app/evenotification/evenotification_test.go
internal/app/evenotification/links.go
internal/app/evenotification/tower_test.go
internal/app/eveuniverse/eveentity.go
internal/app/eveuniverse/eveentity_test.go
internal/app/ui/updateticker.go
main.go

- Fixes issue #3 
- Adds character name in desktop notification
- Refactors and improves notification tests

Fix issue 3

---

FyneApp.toml
internal/app/character/characterskillqueue.go
internal/app/character/characterskillqueue_internal_test.go
internal/app/storage/characterskillqueueitem.go
internal/app/storage/characterskillqueueitem_test.go
internal/app/storage/testutil/factory.go
internal/app/ui/account.go
internal/app/ui/assets.go
internal/app/ui/assetsearch.go
internal/app/ui/attributes.go
internal/app/ui/implants.go
internal/app/ui/jumpclones.go
internal/app/ui/mail.go
internal/app/ui/notifications.go
internal/app/ui/settingswindow.go
internal/app/ui/skillcatalogue.go
internal/app/ui/statuswindow.go
internal/app/ui/typeinfowindow.go
internal/app/ui/ui.go
internal/app/ui/updateticker.go
internal/app/widgets/badge.go
internal/app/widgets/columnslayout.go
internal/app/widgets/slider.go

- Badges for unread counts of mails and communications
- Settings reworked:
- Changes to settings are now effective immediately
- Added buttons for resetting to defaults
- Sliders for numeric values
- Refactoring
- Minimize to Tray disabled by default

Improvements: Badges and settings

---

FyneApp.toml
internal/app/evelocation.go
internal/app/ui/overview.go
internal/app/ui/overview_internal_test.go
internal/app/ui/typeinfowindow.go

- Fixes a crash caused by a character location without a solar system (likely a structure that can no longer be resolved)

Fix issue 7

---

FyneApp.toml
README.md
internal/app/ui/wealth.go
internal/cache/cache.go
internal/cache/cache_internal_test.go
internal/cache/cache_test.go

- Cache cleanup rework for improving stability
- Charts render rework for improving stability
- Pie charts now shown on the same row

Stability update

---

FyneApp.toml
go.mod
go.sum
internal/app/character/charactersection_internal_test.go
internal/app/chartbuilder/chartbuilder.go
internal/app/chartbuilder/chartbuilder_test.go
internal/app/ui/account.go
internal/app/ui/dialoghelper.go
internal/app/ui/menu.go
internal/app/ui/settingswindow.go
internal/app/ui/wealth.go
internal/deleteapp/deleteapp.go
main.go

- Change: Charts are too big on 1080p screens
- Change: Replace toggle widget with switch widget from kx library
- Fix: Show correct data patch on Windows
- Fix: Can not delete crash report on Windows

Use new switch widget and fixes

---

codecov.yml
internal/app/ui/menu.go

- Fix truncated user path shown in dialog
- Stop codecov from failing CI

Fix: Shows truncated user data path

---

FyneApp.toml
internal/app/character/charactersection.go
internal/app/storage/character.go
internal/app/ui/colonies.go
internal/app/ui/locations.go
internal/app/ui/ui.go
internal/app/ui/updateticker.go

- fix: Colonies columns for extracting and producing too small
- fix: Various fields in overview / wallet balance showing as "?"

fix: section refresh and colony ui

---

internal/sso/jose.go
internal/sso/jose_test.go
internal/sso/sso.go
internal/sso/sso_internal_test.go

- Improve error handling in SSO package
- Improve test coverage in SSO package
- Wait with opening browser until web server is running
- Return better errors from SSO package

feat: Improve stability for SSO token authentication & refresh

---

internal/sso/jose.go

Disables the iat validation for JWTs, which is not strictly required and causes occasional false validation errors when the server and local clocks are not in sync

Fix: occasional iat validation error

---

FyneApp.toml
Makefile
internal/app/ui/iteminfo.go
internal/app/ui/mobile/mobile.go
internal/app/ui/settings.go
internal/app/ui/ui.go
internal/app/ui/updateticker.go
internal/app/widget/shipitem.go
internal/sso/sso.go
internal/widget/images.go

- Fix: character selection menu not always updated
- Change: better logging for SSO
- Fix: Disable fastest scaling for mobile (does not work, but generates lots of error spam in logs)

Fixes and improvements

---

internal/app/ui/desktop/desktop.go
internal/app/ui/sendmail.go
internal/app/widget/eveentityentry.go
internal/app/widget/mailheaderitem.go
internal/widget/snackbar.go

- Make snackbars render correctly for longer texts (i.e. automatic multi-line)
- Show icon for mailing lists

Improve snackbar

---

internal/app/character/skillqueue.go
internal/app/character/skillqueue_test.go
internal/app/ui/skillqueue.go

- Moves logic for dealing with a skillqueue to character package
- Fix: Shows invalid status for completed skill queue

Fix: skillqueue showing wrong status after training completed

---

internal/app/characterwallet.go
internal/app/characterwidget/characterwallettransaction.go
internal/app/characterwidget/planetwidget.go
internal/app/collectivewidget/assetsearch.go
internal/app/collectivewidget/clonesearch.go
internal/app/collectivewidget/collectivewidget.go
internal/app/collectivewidget/colonyoverview.go
internal/app/collectivewidget/locationoverview.go
internal/app/collectivewidget/overview.go
internal/app/evegroup.go
internal/app/evesolarsystem.go
internal/app/infowindow/inventorytype.go
internal/app/storage/characterwallettransaction.go
internal/app/storage/queries/character_wallet_transactions.sql
internal/app/storage/queries/character_wallet_transactions.sql.go
internal/app/ui/mobileui.go
internal/widget/tappablerichtext.go

- Improves various pages, e.g. shows all locations with leading system security

Improve pages

---

FyneApp.toml
internal/app/characterasset.go
internal/app/collectivewidget/clonesearch.go
internal/app/infowindow/alliance.go
internal/app/infowindow/character.go
internal/app/infowindow/constellation.go
internal/app/infowindow/corporation.go
internal/app/infowindow/inventorytype.go
internal/app/infowindow/location.go
internal/app/infowindow/region.go
internal/app/infowindow/solarsystem.go
internal/app/storage/queries/character_jump_clones.sql
internal/app/storage/queries/character_jump_clones.sql.go

Fix clone search

---

.gitignore
FyneApp.toml
internal/app/characterservice/charactersection.go
internal/app/characterservice/charactersection_test.go
internal/app/characterui/characterjumpclones.go
internal/app/characterui/charactermail.go
internal/app/characterui/skillqueueitem.go
internal/app/chartbuilder/chartbuilder.go
internal/app/collectionui/wealthoverview.go
internal/app/desktopui/statusbar.go
internal/app/infowindow/alliance.go
internal/app/infowindow/attributelistwidget.go
internal/app/infowindow/character.go
internal/app/infowindow/constellation.go
internal/app/infowindow/corporation.go
internal/app/infowindow/infowindow.go
internal/app/infowindow/location.go
internal/app/infowindow/region.go
internal/app/infowindow/solarsystem.go
internal/app/toolui/usersettings.go
internal/app/ui.go
internal/app/ui/ui.go
internal/sso/sso.go

- Fix attempt for #96 
- Improves logging for sso server

fix: adding character sometimes fails on windows

---

FyneApp.toml
internal/app/evelocation.go
internal/app/evelocation_test.go

This is a bug fix that should resolve #99

fix issue 99

---

internal/app/characterasset.go
internal/app/characterasset_test.go
internal/app/characterservice/asset_internal_test.go
internal/app/storage/characterasset.go
internal/app/storage/characterasset_test.go
internal/app/ui/characterassets.go
internal/app/ui/characterassets_internal_test.go
internal/app/ui/overviewassets.go
internal/app/ui/ui.go
main.go

fix: asset tree crashes when there are multiple items in space

---

internal/app/storage/characterindustryjob.go
internal/app/storage/characterindustryjob_test.go
internal/app/storage/queries/character_industry_jobs.sql
internal/app/storage/queries/character_industry_jobs.sql.go
internal/app/storage/testutil/factory.go
internal/app/ui/colonies.go
internal/app/ui/industryjob.go

fix: fails to fetch industry jobs when locations have no solar systems

---

internal/deleteapp/deleteapp.go
internal/set/set.go

- Migrates delete data app to Fyne 2.6

chore: migrate delete app

---

FyneApp.toml
internal/app/eveuniverseservice/eveuniverseservice.go
internal/app/eveuniverseservice/eveuniverseservice_test.go
internal/app/ui/infowindow.go
internal/app/ui/inventorytypeinfo.go
internal/app/ui/inventorytypeinfo_test.go
internal/app/ui/overviewclones.go
internal/app/ui/ui_internal_test.go
internal/app/ui/ui_test.go

fix: app crashes when trying to show market tab for non-tradeable items

---

internal/app/characterservice/characterservice_internal_test.go
internal/app/eveuniverseservice/eveuniverservice_internal_test.go
internal/app/eveuniverseservice/eveuniverseservice.go
internal/app/eveuniverseservice/eveuniverseservice_test.go
internal/app/ui/infowindow.go

- Improves test coverage, mainly in eveuniverse package
- Refactors httomock usage
- Replaces GetCharacterESI with GetCharacterOrCreateESI in character info window

test: improve test coverage

---

Makefile
internal/app/ui/charactercommunications.go
internal/app/ui/charactermails.go
internal/app/ui/characterskillcatalogue.go
internal/app/ui/characterwalletjournal.go
internal/app/ui/desktopui.go
internal/app/ui/infowindow.go
internal/app/ui/inventorytypeinfo.go
internal/app/ui/mobileui.go
internal/app/ui/ui.go
internal/app/ui/updatestatus.go

- Fix various stability bugs, e.g. caused by data races
- Improve performance of info window
- Improve performance of update status window

fix: various Fyne 2.6 stabilty & performance issues

---

internal/app/ui/infowindow.go

Adds ability to clicking on any name of an info window. The name will then be copied to the clipboard.
This might be useful to search for an object that is shown in EVE Buddy in another client like the Eve client.

feat: copy info name to clipboard

---

internal/app/characterservice/characterservice_internal_test.go
internal/app/characterservice/characterservice_test.go
internal/app/settings/settings_test.go
internal/app/storage/characterasset_test.go
internal/app/storage/charactercontract_test.go
internal/app/storage/characterimplant_test.go
internal/app/storage/charactermail_test.go
internal/app/storage/charactermaillist_test.go
internal/app/storage/characternotification_test.go
internal/app/storage/characterrole_test.go
internal/app/storage/characterwalletjournal_test.go
internal/app/storage/characterwallettransaction_test.go
internal/app/storage/eveentity_test.go
internal/app/storage/planetpin_test.go
internal/set/set.go
internal/set/set_test.go

Remove potentially unsafe comparison of set values

feat: improve set package

---

internal/app/characterservice/character.go
internal/app/eveuniverseservice/eveuniverseservice.go
internal/app/ui/managecharacters.go
internal/app/ui/ui.go
internal/xiter/xiter.go
internal/xiter/xiter_test.go

Reduce wait time after adding new character until dialog is closed and character list is refreshed

perf: manage characters list

---

internal/app/characterservice/character.go
internal/app/corporationservice/corporation.go
internal/app/ui/charactersheet.go
internal/app/ui/desktopui.go
internal/app/ui/industryjob.go
internal/app/ui/mobileui.go
internal/app/ui/overviewassets.go
internal/app/ui/ui.go
internal/widget/navdrawer.go

- Changes main layout:
- "All characters" renamed to "Home" since this Tab now also contains topics with corporation data (i.e. industry jobs)
- "Current Character" now shows the name of the current character
- Adds filter and sorting to industry screen
- Industry tabs for "active" and "all" replaced by filter
- Now shows an indicator on mobile when there are update errors

feat: improve UI

---

FyneApp.toml
README.md
internal/app/ui/desktopui.go
internal/app/ui/mobileui.go

- Fixes a occasional crashe caused by making the Fyne API in goroutines outside a `fyne.Do` callback on desktop
- Fixes a potential data race when calling the Fyne API on mobile

fix: occasional crash

---

FyneApp.toml
internal/app/industry.go
internal/app/ui/industryjob.go
main.go

- fix: sort by industry status not working correctly
- fix: system freezes at startup due to 100% CPU load

fix: industry status sort & high CPU utilization

---

internal/app/characterservice/tag.go
internal/app/eveuniverseservice/eveuniverseservice.go
internal/app/ui/usersettings.go

- Aims to make the UI for managing tags in settings more intuitive
- Refactor of UI code

feat: improve tags UI

---

FyneApp.toml
internal/app/storage/charactertag_test.go
internal/app/storage/testutil/factory.go
internal/app/ui/training.go
internal/app/ui/training_internal_test.go

fix: training inactive filter not working

---

internal/app/character.go
internal/app/character_test.go
internal/app/ui/characterwallettransaction.go
tools/genchars/builder.go

- Changed: Shows totals of market transactions in green for sell and in red for buy. Buy totals are now also negative values.
- Added: Filter for sell/buy market transaction
Fixes #180

feat: distinguish sell/buy market transactions (#180)

---

internal/app/ui/desktopui.go
internal/app/ui/helper.go
internal/app/ui/managecharacters.go
internal/app/ui/mobileui.go
internal/app/ui/statusbar.go
internal/app/ui/ui.go
internal/app/ui/usersettings.go

- Change: The manage characters feature is now also a window on mobile
- Change: Moves the ability to create and configure character tags from settings into the characters window
- Change: Improve tags UI
Fixes #178

feat: Move tags into manage characters window

---

FyneApp.toml
internal/app/storage/characterasset.go
internal/app/storage/charactercontract.go
internal/app/storage/characterimplant.go
internal/app/storage/characterjumpclone.go
internal/app/storage/evelocation.go
internal/app/storage/evemarketprice.go
internal/app/storage/eveplanet.go
internal/app/storage/eveschematic.go
internal/app/storage/eveshipskill.go
internal/app/storage/evesolarsystem.go
internal/app/storage/evetypedogmaattribute.go
internal/app/storage/evetypedogmaeffect.go
internal/app/storage/nulltypes.go
internal/app/storage/planetpin.go
internal/app/ui/assets.go
internal/app/ui/characterwalletjournal.go
internal/app/ui/contracts.go
internal/app/ui/infowindow.go
internal/app/ui/locations.go

fix: some detail windows can only be shown once on mobile

---

FyneApp.toml
internal/app/characterservice/character_test.go
internal/app/characterservice/communications.go
internal/app/characterservice/communications_internal_test.go
internal/app/characterservice/communications_test.go
internal/app/characterservice/contracts.go
internal/app/characterservice/contracts_test.go
internal/app/characterservice/mail.go
internal/app/characterservice/mail_test.go
internal/app/characterservice/skills.go
internal/app/characterservice/skills_test.go
internal/app/eveuniverseservice/character.go
internal/app/eveuniverseservice/character_internal_test.go
internal/app/eveuniverseservice/character_test.go
internal/app/statuscacheservice/statuscache_test.go
internal/app/storage/evecharacter.go
internal/app/ui/charactersheet.go
internal/app/ui/clones.go
internal/app/ui/corporationsheet.go
internal/app/ui/industryslot.go
internal/app/ui/statusbar.go
internal/app/ui/updatestatus.go
internal/widget/navdrawer.go
main_test.go
tools/genchars/main.go

Fixes #189 
Fix attempt for #186

fix: character update and duplicate notifications

---

FyneApp.toml
README.md
internal/app/eveuniverseservice/eveuniverservice_internal_test.go
internal/app/eveuniverseservice/type_internal_test.go
internal/app/ui/assets.go
internal/app/ui/characterassets.go
internal/app/ui/clones.go
internal/app/ui/colonies.go
internal/app/ui/contracts.go
internal/app/ui/helper.go
internal/app/ui/industryjob.go
internal/app/ui/infowindow.go
internal/app/ui/training.go
internal/app/ui/ui.go
internal/app/ui/walletjournal.go
internal/app/ui/wallettransaction.go

- Now shows a detail window for assets both from the home asset and the character asset screen
- Market prices where updated every 30 seconds, causing unnecessary refreshes
- Wrong character shows in type info window when showing details for a skill in training from the home menu (#201)

feat: improve detail windows

---

main.go
main_test.go

When logging responses from ESI the app is currently printing the body as escaped JSON string. For example:
```
body="[{\"alliance_id\":99010928,\"character_id\":2122561977,\"corporation_id\":98716618,\"faction_id\":500011}]"
```
This is fairly hard to read for debugging.
This PR changes the output to un-marshalled Go structs, which are shorter and don't require esacping. For example:
```
[map[alliance_id:9.9010928e+07 character_id:2.122561977e+09 corporation_id:9.8716618e+07 faction_id:500011]]
```

feat: better response logging

---

go.mod
go.sum
internal/app/evenotification/billing.go
internal/app/evenotification/corporate.go
internal/app/evenotification/moonmining.go
internal/app/evenotification/orbital.go
internal/app/evenotification/sov.go
internal/app/evenotification/structure.go
internal/app/evenotification/tower.go
internal/app/evenotification/war.go

feat: replace yaml library

---

FyneApp.toml
internal/app/ui/marketorders.go

feat: show order totals

---

internal/app/characterservice/market_internal_test.go
internal/app/storage/charactermarketorder_test.go
internal/app/storage/queries/character_market_orders.sql
internal/app/storage/queries/character_market_orders.sql.go
internal/app/ui/corporationmember.go
internal/app/ui/infowindow.go
internal/app/ui/managecharacters.go

fix: market order price update

---

internal/app/characterservice/token.go
internal/app/sso/sso.go
internal/app/sso/tmpl/authenticated.html
internal/app/ui/augmentations_internal_test.go
internal/app/ui/characterassets_internal_test.go
internal/app/ui/characteraugmentations_internal_test.go
internal/app/ui/characterbiography_internal_test.go
internal/app/ui/characterlocations_internal_test.go
internal/app/ui/charactermails_internal_test.go
internal/app/ui/characteroverview_internal_test.go
internal/app/ui/corporationmember_internal_test.go
internal/app/ui/corporationwallet_internal_test.go
internal/app/ui/desktop_internal_test.go
internal/app/ui/desktopui.go
internal/app/ui/desktopui_test.go
internal/app/ui/industryjob_internal_test.go
internal/app/ui/industryslot_internal_test.go
internal/app/ui/managecharacters.go
internal/app/ui/managedcharacters_internal_test.go
internal/app/ui/mobileui.go
internal/app/ui/statusbar.go
internal/app/ui/toolbar.go
internal/app/ui/ui.go
internal/app/ui/wallettransaction_internal_test.go

- Added: Shows a warning on desktop and mobile when characters are missing scopes
- Fixed: Adopts completion page to new SSO page layout
- Fixed: Window resize on desktop not always resizing the full page content

feat: show missing scope indicator

---

internal/app/ui/assets.go
internal/app/ui/characterlocations.go
internal/app/ui/characteroverview.go
internal/app/ui/colonies.go
internal/app/ui/contracts.go
internal/app/ui/corporationstructures.go
internal/app/ui/desktopui.go
internal/app/ui/helper.go
internal/app/ui/industryslot.go
internal/app/ui/marketorders.go
internal/app/ui/training.go
internal/app/ui/wallettransaction.go

fix: column name sort
