FyneApp.toml, internal/app/ui/assetsearch.go, internal/app/ui/mail.go, internal/app/ui/overview.go, internal/app/ui/resource.go, internal/app/ui/walletjournal.go, internal/app/ui/wallettransaction.go, resources/ui/sort-ascending.svg, resources/ui/sort-descending.svg, resources/ui/sort.svg
- Improves performance of all tables, i.e. by no longer using ellipsis truncation, which is very slow (#22)
- Uses better icons for representing sort in asset search
- Removes ability to jump directly to a character & page by clicking into the overview table
=> Change: Improve performance of all tables

internal/app/character/characterasset.go, internal/app/character/characterjumpclone.go, internal/app/character/characterjumpclone_internal_test.go, internal/app/character/characterskills.go, internal/app/storage/characterjumpclone_test.go, internal/app/storage/characterwalletjournal.go, internal/app/storage/testutil/factory.go, internal/app/ui/jumpclones.go
The current asset update loop deletes obsolete assets with every asset. That is slow and unnecessary. With this PR obsolete assets are removed only once per update.
=> Improve obsolete asset deletion

internal/app/ui/assetsearch.go, internal/app/ui/locations.go, internal/app/ui/overview.go, internal/app/ui/training.go, internal/app/ui/ui.go, internal/app/ui/updateticker.go
- Move location information from overview tab into new "Locations" tab
- Move training information from overview tab into new "Training" tab
- Improve update logic for tabs under "Characters"
In part addresses the feature request in #8
=> feat: Show locations and training for characters in own tabs

FyneApp.toml, codecov.yml, go.mod, go.sum
- Update to Fyne [2.5.3](https://github.com/fyne-io/fyne/releases/tag/v2.5.3)
- Now shows better menu shortcuts on Linux and Windows
- Various bug fixes and performance improvements
- ...
- Remove UI from test coverage tracking
=> feat: Update to Fyne 2.5.3

internal/httptransport/http.go, internal/httptransport/http_test.go, internal/sso/jose.go, internal/sso/sso.go, main.go
Allow a small time difference between local and server time when validating JWTs.
Fixes #46
=> fix: Allow small time difference when validating tokens

FyneApp.toml, internal/app/character/character.go, internal/app/character/charactertoken.go, internal/app/character/charactertoken_internal_test.go, internal/set/set.go, internal/set/set_test.go, internal/sso/sso.go
The web server may shut down during the SSO process when receiving an unexpected request (e.g. /favicon). With this patch the web server will continue to log unexpected requests, but no longer abort the SSO process.
=> chore: improve sso stability

.gitignore, main.go
- The windows release version does not write log files, while the development version does
- This fix re-enables file logging for windows
=> fix: logs are not written on windows

internal/app/ui/characterwallettransaction.go
Totals in the wallet transactions table are always showing as positive value, even when item is bought.
=> fix: wallet transaction total always positive

internal/sso/logger.go, internal/sso/sso.go, internal/sso/template/authenticated.html, internal/sso/tmpl/authenticated.html, main.go
Adds a landing page that is shown to users when they completed the SSO process successfully.
The landing page uses the original styling from the Eve online login page to not break the user experience.
Screenshot
=> feat: add sso landing page

internal/app/app.go, internal/app/characterservice/character.go, internal/app/characterservice/character_test.go, internal/app/characterservice/contract_test.go, internal/app/characterservice/jumpclone_internal_test.go, internal/app/characterservice/skillqueue_test.go, internal/app/statuscacheservice/statuscache_test.go, internal/app/storage/character.go, internal/app/storage/character_test.go, internal/app/storage/queries/characters.sql, internal/app/storage/queries/characters.sql.go, internal/app/storage/testutil/factory.go, tools/genchars/builder.go
This PR replaces the UpdateOrCreateCharater() method with a CreateCharater() and makes it return a new error code `app.ErrAlreadyExists` to signal when the character already exists.
=> fix: some char data is deleted when re-adding a char

FyneApp.toml, internal/app/ui/characterassets.go, internal/app/ui/characterassets_internal_test.go
Alternative fix for issue reporting in #113
=> fix: asset tree widget crashes when no character

Makefile, internal/app/settings.go, internal/app/settings/settings.go, internal/app/ui/infowindow/infowindow.go, internal/app/ui/infowindow/inventorytype.go, internal/app/ui/usersettings.go
Users can choose to always show the market tab first when opening an info window for a trade-able type.
This can be configured through a setting.
Fixes #126
=> feat: config for prefering market tabs

internal/app/characterservice/characterservice_internal_test.go, internal/app/eveuniverseservice/eveuniverseservice.go, internal/app/storage/character.go, internal/app/storage/characterasset.go, internal/app/storage/charactercontractbid.go, internal/app/storage/charactermail.go, internal/app/storage/characternotification.go, internal/app/storage/characterskill.go, internal/app/storage/characterwalletjournal.go, internal/app/storage/characterwallettransaction.go, internal/app/storage/evecharacter.go, internal/app/storage/eveentity.go, internal/app/ui/overviewlocations.go, internal/app/ui/usersettings.go, internal/deleteapp/deleteapp.go, internal/set/set.go, internal/set/set_test.go
The current set type needs to be initialized with New(). If a zero value of a set is used in the wrong way it will panic.
This PR improves the set type so that the zero value is an empty set and can be used normally.
It also adds MustPop() to the API.
And it improves the test suite and documentation for the set package.
=> feat: improve set type

internal/app/characterservice/character.go, internal/app/characterservice/character_internal_test.go, internal/app/corporationservice/corporation.go, internal/app/corporationservice/corporation_internal_test.go, internal/app/eveuniverseservice/eveuniverseservice.go, internal/app/ui/industryjob.go, internal/app/ui/ui.go, internal/app/ui/updatestatus.go, internal/widget/contextmenu.go
- Fix: forcing an update of a corporation section is not working
- Change: the job status is now fixed when receiving data from ESI, so the jobs are stored in the DB with the corrected status
- Added: Ability to force update all entities at once
> [!NOTE]  
> All industry jobs need to be force updated to ensure they have the correct status. Tip: This can be done quickly with the new "Update all" feature
=> feat: ability to update all entities at once & fixes

internal/app/app.go, internal/app/character.go, internal/app/characterservice/character.go, internal/app/eveuniverseservice/location.go, internal/app/storage/charactercontract_test.go, internal/app/storage/queries/character_contracts.sql, internal/app/storage/queries/character_contracts.sql.go, internal/app/ui/characterwalletjournal.go, internal/app/ui/characterwallettransaction.go, internal/app/ui/contracts.go, internal/app/ui/helper.go, internal/app/ui/industryjob.go, internal/app/ui/mobileui.go, internal/set/set.go, internal/stack/stack.go, internal/stack/stack_test.go, internal/widget/appbar.go, internal/widget/navbar.go, tools/genchars/builder.go
- Re-design of the wallet lists for mobile (both wallet journal and wallet transactions) to make it easier to read, fit more entries on the screen and improve scroll performance
- Tapping an entry now opens a window with details for each entry. Works both for mobile and desktop.
- Adds context links for both journal entries and transactions. e.g. journal entries can link to a related contract or transaction, transaction can link to the related journal entry
- Technical: Navigator widget now supports hiding the navbar on nested pages
=> feat: improve wallet lists on mobile

FyneApp.toml, internal/app/settings/settings.go, internal/app/settings/settings_test.go, internal/app/ui/ui.go, internal/app/ui/usersettings.go
Adds a color theme switcher with the options:
- Auto (= current OS theme)
- Light
- Dark
=> feat: Add theme switcher

FyneApp.toml, internal/app/ui/characterskillqueue.go, internal/app/ui/locations.go
- Training mobile: Progress bar of active entry can appear inside entry of inactive entry
=> fix: skill progress bar shown in inactive skills

FyneApp.toml, internal/app/characterservice/character_internal_test.go, internal/app/characterservice/character_test.go, internal/app/corporationservice/corporation.go, internal/app/corporationservice/corporation_internal_test.go, internal/app/industry.go, internal/app/storage/characterindustryjob_test.go, internal/app/storage/testutil/factory.go, internal/app/ui/industryjob.go, internal/app/ui/industryjob_internal_test.go, main.go
This fixes a bug where some reactions where not detected correctly, i.e. not showing up in the slots calculation and their activity label shown as "?".
Relates to this known quirk in ESI: [Industry jobs activity id changed to enum](https://github.com/esi/esi-issues/issues/894)
=> fix: some reactions not detected

FyneApp.toml, internal/app/characterskill.go, internal/app/characterskill_test.go, internal/app/storage/characterskillqueueitem.go, internal/app/ui/characterskillqueue.go, internal/app/ui/training.go
The calculation of the queue time is simplified and directly taking from the ESI response. This should fix #182 .
=> fix: remaining queue time not always correct (#182)

FyneApp.toml, go.mod, go.sum, internal/app/characterservice/character.go, internal/app/ui/assets.go, internal/app/ui/characterjumpclones.go, internal/app/ui/characterlocations.go, internal/app/ui/characterlocations_internal_test.go, internal/app/ui/characteroverview.go, internal/app/ui/characteroverview_internal_test.go, internal/app/ui/characters.go, internal/app/ui/characterskillqueue.go, internal/app/ui/clones.go, internal/app/ui/colonies.go, internal/app/ui/contracts.go, internal/app/ui/corporationsheet.go, internal/app/ui/desktopui.go, internal/app/ui/detailwindow.go, internal/app/ui/gamesearch.go, internal/app/ui/helper.go, internal/app/ui/industryjob.go, internal/app/ui/locations.go, internal/app/ui/mobileui.go, internal/app/ui/training.go, internal/app/ui/ui.go, internal/app/ui/walletjournal.go, internal/app/ui/wallettransaction.go, internal/humanize/humanize.go
- Detail window now shows a context image, e.g. character portrait for character location detail
- Clicking on a row in Home / Training now shows the training queue for that character (#201)
- Clicking on a row in Home / Location now shows a detail window
- Clicking on a row in Home / Character Overview now shows a detail window
- Clarified names of menu options in Home list
- Potential duplicate window IDs may result in weird behavior when opening a detail window
- Corp was not loaded when adding character with NPC corp
Fixes #201
=> feat: improve detail windows & fixes
